// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "MoveIntake.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

MoveIntake::MoveIntake() : Subsystem("MoveIntake") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    raiseLowerI1 = RobotMap::moveIntakeRaiseLowerI1;
    raiseLowerI2 = RobotMap::moveIntakeRaiseLowerI2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    move = true;
}

void MoveIntake::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void MoveIntake::raiseIn()
{
	raiseLowerI1->Set(DoubleSolenoid::kForward);
	raiseLowerI2->Set(DoubleSolenoid::kForward);
	move = true;
}

void MoveIntake::lowerIn()
{
	raiseLowerI1->Set(DoubleSolenoid::kReverse);
	raiseLowerI2->Set(DoubleSolenoid::kReverse);
	move = false;
}




// Put methods for controlling this subsystem
// here. Call these from Commands.

